Mb 4070
AArkh/inspections pull request #2
Opened 2020-04-06 08:30 UTC by AArkh

2020-04-06 08:33 UTC, salonkasoli commented on .idea/compiler.xml
> +    <bytecodeTargetLevel>
привет шо зща фигня?

2020-04-08 03:43 UTC, Kazemir requested changes

2020-04-08 03:43 UTC, Kazemir commented on src/main/resources/inspectionDescriptions/KotlinDangerousMethod.html
> +<p>Text after this comment will only be shown in the settings of the inspection.</p>
Забыль?

2020-04-08 03:43 UTC, Kazemir commented on build.gradle
> +    //alternativeIdePath '/Applications/Android Studio.app/Contents'
А для чего это? Может коммент?

2020-04-08 03:43 UTC, Kazemir commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +class KotlinDangerousMethodInspection : AbstractKotlinInspection() {
Предлагаю подписать комментарий к каждой инспекции и фиксу

2020-04-08 03:43 UTC, Kazemir commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +class KotlinDangerousMethodInspection : AbstractKotlinInspection() {
Можно указать в доке ссылку на соответствующее фиксы/инспекции

2020-04-08 03:43 UTC, Kazemir commented on src/main/java/com/plugin/inspection/fix/KotlinCallExpressionTryCatchQuickFix.kt
> +		}
А почему игнорим?

2020-04-08 03:43 UTC, Kazemir commented on src/main/java/com/plugin/inspection/fix/KotlinCallExpressionTryCatchQuickFix.kt
> +		}
Может если не игнорить, то студия красивую плашечку выведет )

2020-04-08 03:43 UTC, Kazemir commented on src/main/java/com/plugin/inspection/fix/KotlinAddExceptionToThrowAnnotationQuickFix.kt
> +		}
и туть

2020-04-08 03:43 UTC, Kazemir commented on src/main/java/com/plugin/inspection/fix/AnnotateDangerousMethodQuickFix.kt
> +		}
везде

2020-04-08 03:43 UTC, Kazemir commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +		}
тыщи их

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +				val method = expression.getContainingMethod() ?: return
Типы бы везде проставить не помешало

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +				val exceptionNames: List<String> = exceptionTypes.map { psiClass: PsiClass ->
Может тут сделать `mapNotNull`, чтобы не словить краш случайно?

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +				for (name: String in exceptionNames) {
Можно сделать так `exceptionNames.find { exceptionReferences.contains(it) } ?: return`. Локаничнее и понятнее

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +			override fun visitThrowExpression(expression: KtThrowExpression) {
если есть возможно разнести код по методам, было бы круто

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +		val set = LinkedHashSet<String>()
А нельзя сращу List использовать? Или есть вероятность дублирования?

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +			val resolved: PsiElement = currentThrownExceptionReference.resolve() ?: return null
resolved как какой-то boolean. Го название ассоциированное с `PsiElement`

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +			} ?: return null
`?: return null` излишне. А еще предлагаю  писать в 1 строку `is KtTypeAlias -> resolved.retrievePsiClass()`

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinThrowsMethodInspection.kt
> +				val reference: KtReference = expression.calleeExpression?.mainReference ?: return
может сразу `.resolve() ?: return`?

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/KotlinThrowsMethodInspection.kt
> +				if (calledElement !is KtNamedFunction
предлагаю услоие в метод вынести

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/fix/KotlinAddExceptionToThrowAnnotationQuickFix.kt
> +			val replacementAnnotation = psiFactory.createAnnotationEntry("@Throws")
Предлагаю расставить типы и если можно, разнести по методам

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/fix/KotlinCallExpressionTryCatchQuickFix.kt
> +			val elementsToBeSurrounded = when(elementToBeFixed) {
тип

2020-04-08 04:12 UTC, AlexeyPanchenko commented on src/main/java/com/plugin/inspection/fix/KotlinAddExceptionToThrowAnnotationQuickFix.kt
> +		val arguments = descriptor.allValueArguments.values
типы

2020-04-08 06:45 UTC, AArkh commented on src/main/resources/inspectionDescriptions/KotlinDangerousMethod.html
> +<p>Text after this comment will only be shown in the settings of the inspection.</p>
Ага, выпилил

2020-04-08 06:51 UTC, AArkh commented on build.gradle
> +    //alternativeIdePath '/Applications/Android Studio.app/Contents'
Для тестирования плагина запускается таска "runIde". По умолчанию запускается экземпляр той intelliJ IDEA, с которой ты работаешь. Этой переменной можно задать путь к другой IDEA-like ide'шке и для тестирования использовать её. Закомменчено, т.к. мой путь к студии может отличаться от вашего. Добавил коммент туда.

2020-04-08 07:04 UTC, AArkh commented on src/main/java/com/plugin/inspection/fix/KotlinCallExpressionTryCatchQuickFix.kt
> +		}
Всмысле, красивую плашечку "я взарвался"? любой resolve и создание Psi штук крашатся, поэтому я без задней мысли обернул все это дело. Но наверное да, набо убрать.

2020-04-08 07:08 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +class KotlinDangerousMethodInspection : AbstractKotlinInspection() {
Добавил кратенькую доку

2020-04-08 07:08 UTC, AArkh commented on src/main/java/com/plugin/inspection/fix/KotlinAddExceptionToThrowAnnotationQuickFix.kt
> +		}
ага

2020-04-08 07:08 UTC, AArkh commented on src/main/java/com/plugin/inspection/fix/AnnotateDangerousMethodQuickFix.kt
> +		}
убрал

2020-04-08 07:08 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +		}
++

2020-04-08 07:14 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +				val method = expression.getContainingMethod() ?: return
Попроставлял

2020-04-08 07:16 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +				val exceptionNames: List<String> = exceptionTypes.map { psiClass: PsiClass ->
Там у .getExceptionReferences() тип возврата - List<String> , нулл по контракту не может быть

2020-04-08 07:19 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +				for (name: String in exceptionNames) {
Ага, сделал так

2020-04-08 07:21 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +		val set = LinkedHashSet<String>()
Вероятность есть, но не критичная. Тут раньше немного иная логика была, сделал через список

2020-04-08 07:22 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +			val resolved: PsiElement = currentThrownExceptionReference.resolve() ?: return null
resolvedExceptionClass

2020-04-08 07:23 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +			} ?: return null
ага

2020-04-08 07:24 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinThrowsMethodInspection.kt
> +				val reference: KtReference = expression.calleeExpression?.mainReference ?: return
Давай так

2020-04-08 07:29 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinThrowsMethodInspection.kt
> +				if (calledElement !is KtNamedFunction
ага

2020-04-08 07:34 UTC, AArkh commented on src/main/java/com/plugin/inspection/fix/KotlinAddExceptionToThrowAnnotationQuickFix.kt
> +			val replacementAnnotation = psiFactory.createAnnotationEntry("@Throws")
аннотировал, вынес один метод.

2020-04-08 07:34 UTC, AArkh commented on src/main/java/com/plugin/inspection/fix/KotlinCallExpressionTryCatchQuickFix.kt
> +			val elementsToBeSurrounded = when(elementToBeFixed) {
ага

2020-04-08 07:34 UTC, AArkh commented on src/main/java/com/plugin/inspection/fix/KotlinAddExceptionToThrowAnnotationQuickFix.kt
> +		val arguments = descriptor.allValueArguments.values
ага

2020-04-09 00:07 UTC, AArkh commented on src/main/java/com/plugin/inspection/fix/KotlinAddExceptionToThrowAnnotationQuickFix.kt
> +			val replacementAnnotation = psiFactory.createAnnotationEntry("@Throws")
Еще немного подразнес.

2020-04-09 00:25 UTC, AArkh commented on src/main/java/com/plugin/inspection/KotlinDangerousMethodInspection.kt
> +			override fun visitThrowExpression(expression: KtThrowExpression) {
Подразнес

2020-04-09 02:28 UTC, Kazemir approved these changes

2020-04-13 01:39 UTC, merged